platform:ios,'8.0'

target 'CHChatKit' do    

pod 'UITableView+FDTemplateLayoutCell'
pod 'SDWebImage', '~> 3.8.2'
pod 'Masonry'
pod 'XEBEventBus'
pod 'Realm'
pod 'CHImagePicker'

pod 'CHChatKit', :path => '../'

end

target 'CHChatKitTests' do
    
end
