platform:ios,'8.0'

target 'CHChatKit' do    

pod 'UITableView+FDTemplateLayoutCell'
pod 'SDWebImage', "~> 3.8.2"
pod 'Masonry'
pod 'XEBEventBus'
pod 'Realm', "~> 2.1.2"
pod 'CHImagePicker'
pod 'CHProgressHUD'
pod 'CHChatKit', :path => '../'

end

target 'CHChatKitTests' do
    
end
